name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      SPACK_ROOT: spack
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          buildcache: true
          color: true
          path: ${{ env.SPACK_ROOT }}
      - name: Install osparc package
        run: ./install.sh
      - name: Test osparc package
        run: |
          source "${{ env.SPACK_ROOT }}/share/spack/setup-env.sh"
          spack load osparc
          osparc-build
